name: local_buzz_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  google_sign_in: ^6.1.4
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  timeago: ^3.7.1
  share_plus: ^11.0.0
  percent_indicator: ^4.2.5
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  package_info_plus: ^8.3.0
  rxdart: ^0.28.0
  flutter_animate: ^4.5.2
  glassmorphism: ^3.0.0
  animated_icon_button: ^1.0.2
  glassmorphism_ui: ^0.3.0
  font_awesome_flutter: ^10.8.0
  like_button: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
