// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQImLY6AyiabIPj-mmgHPJK0HgT0Vc1F0',
    appId: '1:638822421166:web:b8cc9c60fa00c80a82533f',
    messagingSenderId: '638822421166',
    projectId: 'localbuzzapp',
    authDomain: 'localbuzzapp.firebaseapp.com',
    storageBucket: 'localbuzzapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSJfx5mpT2Ka0tyP85kYgy_UzkzZMoKBM',
    appId: '1:638822421166:android:7805753d0ed8da0682533f',
    messagingSenderId: '638822421166',
    projectId: 'localbuzzapp',
    storageBucket: 'localbuzzapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ4U_3eRkv0vc4N4y-PLoqiqTExjkjdhs',
    appId: '1:638822421166:ios:8b79eb24cf07f3b982533f',
    messagingSenderId: '638822421166',
    projectId: 'localbuzzapp',
    storageBucket: 'localbuzzapp.firebasestorage.app',
    androidClientId: '638822421166-ofa28mj5dnj4asef4eknd0rj5i05l4i4.apps.googleusercontent.com',
    iosClientId: '638822421166-terq4ororhv9u45ao6bfcen1krj098p5.apps.googleusercontent.com',
    iosBundleId: 'com.example.localBuzzApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ4U_3eRkv0vc4N4y-PLoqiqTExjkjdhs',
    appId: '1:638822421166:ios:8b79eb24cf07f3b982533f',
    messagingSenderId: '638822421166',
    projectId: 'localbuzzapp',
    storageBucket: 'localbuzzapp.firebasestorage.app',
    androidClientId: '638822421166-ofa28mj5dnj4asef4eknd0rj5i05l4i4.apps.googleusercontent.com',
    iosClientId: '638822421166-terq4ororhv9u45ao6bfcen1krj098p5.apps.googleusercontent.com',
    iosBundleId: 'com.example.localBuzzApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQImLY6AyiabIPj-mmgHPJK0HgT0Vc1F0',
    appId: '1:638822421166:web:e992d92a22675b9982533f',
    messagingSenderId: '638822421166',
    projectId: 'localbuzzapp',
    authDomain: 'localbuzzapp.firebaseapp.com',
    storageBucket: 'localbuzzapp.firebasestorage.app',
  );
}
