// import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'package:firebase_auth/firebase_auth.dart';
// import 'screens/login_screen.dart';
// import 'screens/home_screen.dart';

// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   await Firebase.initializeApp(); // ✅ no options
//   runApp(const MyApp());
// }

// class MyApp extends StatelessWidget {
//   const MyApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'LocalBuzz',
//       theme: ThemeData(primarySwatch: Colors.blue),
//       home: StreamBuilder<User?>(
//         stream: FirebaseAuth.instance.authStateChanges(),
//         builder: (context, snapshot) {
//           if (snapshot.connectionState == ConnectionState.waiting) {
//             return const Scaffold(
//               body: Center(child: CircularProgressIndicator()),
//             );
//           } else if (snapshot.hasData) {
//             return  HomeScreen();
//           } else {
//             return const LoginScreen();
//           }
//         },
//       ),
//     );
//   }
// }


// lib/main.dart
// import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'package:firebase_auth/firebase_auth.dart';

// import 'screens/login_screen.dart';
// import 'screens/home_screen.dart';
// //import 'firebase_options.dart'; // auto-generated by FlutterFire CLI

// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   await Firebase.initializeApp(
//    // options: DefaultFirebaseOptions.currentPlatform,
//   );
//   runApp(const MyApp());
// }

// class MyApp extends StatelessWidget {
//   const MyApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'LocalBuzz',
//       theme: ThemeData(
//         primarySwatch: Colors.deepPurple,
//       ),
//       home: StreamBuilder<User?>(
//         stream: FirebaseAuth.instance.authStateChanges(),
//         builder: (context, snapshot) {
//           if (snapshot.connectionState == ConnectionState.waiting) {
//             return const Scaffold(body: Center(child: CircularProgressIndicator()));
//           } else if (snapshot.hasData) {
//             return  HomeScreen(); // user is logged in
//           } else {
//             return const LoginScreen(); // user not logged in
//           }
//         },
//       ),
//       debugShowCheckedModeBanner: false,
//     );
//   }
// }



// import 'package:flutter/material.dart';
// import 'package:local_buzz_app/screens/login_screen.dart';

// void main() {
//   runApp(const MyApp());
// }

// class MyApp extends StatelessWidget {
//   const MyApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'LocalBuzz',
//       debugShowCheckedModeBanner: false,
//       themeMode: ThemeMode.system,
//       theme: ThemeData(
//         brightness: Brightness.light,
//         scaffoldBackgroundColor: Colors.white,
//         appBarTheme: const AppBarTheme(
//           backgroundColor: Colors.white,
//           foregroundColor: Colors.black,
//           elevation: 1,
//         ),
//         iconTheme: const IconThemeData(color: Colors.black),
//         textTheme: const TextTheme(
//           bodyMedium: TextStyle(color: Colors.black),
//         ),
//         useMaterial3: true,
//       ),
//       darkTheme: ThemeData(
//         brightness: Brightness.dark,
//         scaffoldBackgroundColor: Colors.black,
//         appBarTheme: const AppBarTheme(
//           backgroundColor: Colors.black,
//           foregroundColor: Colors.white,
//           elevation: 0,
//         ),
//         iconTheme: const IconThemeData(color: Colors.white),
//         textTheme: const TextTheme(
//           bodyMedium: TextStyle(color: Colors.white),
//         ),
//         useMaterial3: true,
//       ),
//       home: const LoginScreen(),
//     );
//   }
// }



// import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'package:firebase_auth/firebase_auth.dart';
// import 'package:local_buzz_app/screens/home_feed_screen.dart';

// import 'package:local_buzz_app/screens/login_screen.dart';
// import 'package:local_buzz_app/bottomnav.dart';
// import 'package:local_buzz_app/screens/my_profile_screen.dart';
// import 'package:local_buzz_app/screens/otherscreens/bookmarks_provider.dart';
// import 'package:local_buzz_app/screens/otherscreens/likes_provider.dart';
// import 'package:local_buzz_app/screens/otherscreens/notification_seen_provider.dart';
// import 'package:local_buzz_app/screens/otherscreens/post_provider.dart';
// import 'package:local_buzz_app/screens/public_user_pofile.dart';
// import 'package:provider/provider.dart';

// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   await Firebase.initializeApp();
//   runApp(
//     MultiProvider(providers: 
//     [
//       ChangeNotifierProvider(
//         create: (_) => NotificationSeenProvider()),
//         ChangeNotifierProvider(
//         create: (_) => LocationProvider()),
        
//       ChangeNotifierProvider(
//         create: (_) => BookmarksProvider()),

//         ChangeNotifierProvider(
//         create: (_) => LikesProvider()),

//         ChangeNotifierProvider(
//         create: (_) => LikeNotifier()),

//         ChangeNotifierProvider(
//         create: (_) => MyProfileLikeNotifier()),
        

//         ChangeNotifierProvider(
//         create: (_) => PostProvider( )),

      
//     ],
//       child:    const MyApp(),
//       ),
//     );

// }

// class MyApp extends StatelessWidget {
//   const MyApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'LocalBuzz',
//       debugShowCheckedModeBanner: false,
//       themeMode: ThemeMode.system,                
//       theme: ThemeData(
//         brightness: Brightness.light,
//         scaffoldBackgroundColor: Colors.white,
//         appBarTheme: const AppBarTheme(
//           backgroundColor: Colors.white,
//           foregroundColor: Colors.black,
//           elevation: 1,
//         ),
//         iconTheme: const IconThemeData(color: Colors.black),
//         textTheme: const TextTheme(
//           bodyMedium: TextStyle(color: Colors.black),
//         ),
//         useMaterial3: true,
//       ),
//       darkTheme: ThemeData(
//         brightness: Brightness.dark,
//         scaffoldBackgroundColor: Colors.black,
//         appBarTheme: const AppBarTheme(
//           backgroundColor: Colors.black,
//           foregroundColor: Colors.white,
//           elevation: 0,
//         ),
//         iconTheme: const IconThemeData(color: Colors.white),
//         textTheme: const TextTheme(
//           bodyMedium: TextStyle(color: Colors.white),
//         ),
//         useMaterial3: true,
//       ),
//       home: FirebaseAuth.instance.currentUser == null
//           ? const LoginScreen()
//           : const BottomNavScreen(),
//     );
//   }
// }



// import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'package:firebase_auth/firebase_auth.dart';
// import 'package:local_buzz_app/screens/home_feed_screen.dart';
// import 'package:local_buzz_app/screens/my_profile_screen.dart';
// //import 'package:local_buzz_app/screens/private_user_profie.dart';
// import 'package:local_buzz_app/screens/public_user_pofile.dart';
// import 'package:provider/provider.dart';

// import 'package:local_buzz_app/bottomnav.dart';
// import 'package:local_buzz_app/screens/login_screen.dart';
// import 'package:local_buzz_app/screens/otherscreens/bookmarks_provider.dart';
// import 'package:local_buzz_app/screens/otherscreens/likes_provider.dart';
// import 'package:local_buzz_app/screens/otherscreens/notification_seen_provider.dart';
// import 'package:local_buzz_app/screens/otherscreens/post_provider.dart';
// //import 'package:shared_preferences/shared_preferences.dart';


// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   await Firebase.initializeApp();
//   runApp(
//     MultiProvider(
//       providers: [
//         ChangeNotifierProvider(create: (_) => NotificationSeenProvider()),
//         ChangeNotifierProvider(create: (_) => LocationProvider()),
//         ChangeNotifierProvider(create: (_) => BookmarksProvider()),
//         ChangeNotifierProvider(create: (_) => LikesProvider()),
//         ChangeNotifierProvider(create: (_) => LikeNotifier()),
//         ChangeNotifierProvider(create: (_) => MyProfileLikeNotifier()),
//         ChangeNotifierProvider(create: (_) => PostProvider()),
//        // ChangeNotifierProvider(create: (_) => UserProvider()),
//       ],

      
//       child: const MyApp(),
//     ),
//   );
// }

// class MyApp extends StatelessWidget {
//   const MyApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'LocalBuzz',
//       debugShowCheckedModeBanner: false,
//       themeMode: ThemeMode.system,

//       // ✅ Your full light theme
//       theme: ThemeData(
//         brightness: Brightness.light,
//         scaffoldBackgroundColor: Colors.white,
//         appBarTheme: const AppBarTheme(
//           backgroundColor: Colors.white,
//           foregroundColor: Colors.black,
//           elevation: 1,
//         ),
//         iconTheme: const IconThemeData(color: Colors.black),
//         textTheme: const TextTheme(
//           bodyMedium: TextStyle(color: Colors.black),
//         ),
//         useMaterial3: true,
//       ),

//       // ✅ Your full dark theme
//       darkTheme: ThemeData(
//         brightness: Brightness.dark,
//         scaffoldBackgroundColor: Colors.black,
//         appBarTheme: const AppBarTheme(
//           backgroundColor: Colors.black,
//           foregroundColor: Colors.white,
//           elevation: 0,
//         ),
//         iconTheme: const IconThemeData(color: Colors.white),
//         textTheme: const TextTheme(
//           bodyMedium: TextStyle(color: Colors.white),
//         ),
//         useMaterial3: true,
//       ),

//       // ✅ Auth-aware dynamic routing
//       home: StreamBuilder<User?>(
//         stream: FirebaseAuth.instance.authStateChanges(),
//         builder: (context, snapshot) {
//           if (snapshot.connectionState == ConnectionState.waiting) {
//             return const Scaffold(
//               body: Center(child: CircularProgressIndicator()),
//             );
//           } else if (snapshot.hasData) {
//             //Provider.of<NotificationSeenProvider>(context, listen: false).refresh(refresh: true);
//             return const BottomNavScreen();
//           } else {
//             return const LoginScreen();
            
//           }
//         },
//       ),
//     );
//   }
// }


// import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'package:firebase_auth/firebase_auth.dart';
// import 'package:local_buzz_app/allSettings/enter_pin_screen.dart';
// import 'package:local_buzz_app/screens/home_feed_screen.dart';
// import 'package:local_buzz_app/screens/my_profile_screen.dart';
// import 'package:local_buzz_app/screens/otherscreens/theme_provider.dart';
// //import 'package:local_buzz_app/screens/private_user_profie.dart';
// import 'package:local_buzz_app/screens/public_user_pofile.dart';
// import 'package:provider/provider.dart';

// import 'package:local_buzz_app/bottomnav.dart';
// import 'package:local_buzz_app/screens/login_screen.dart';
// import 'package:local_buzz_app/screens/otherscreens/bookmarks_provider.dart';
// import 'package:local_buzz_app/screens/otherscreens/likes_provider.dart';
// import 'package:local_buzz_app/screens/otherscreens/notification_seen_provider.dart';
// import 'package:local_buzz_app/screens/otherscreens/post_provider.dart';

// import 'package:shared_preferences/shared_preferences.dart';

// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   await Firebase.initializeApp();

//   final prefs = await SharedPreferences.getInstance();
//   final savedPin = prefs.getString('app_pin');

//   runApp(
//     MultiProvider(
//       providers: [
//         ChangeNotifierProvider(create: (_) => NotificationSeenProvider()),
//         ChangeNotifierProvider(create: (_) => LocationProvider()),
//         ChangeNotifierProvider(create: (_) => BookmarksProvider()),
//         ChangeNotifierProvider(create: (_) => LikesProvider()),
//         ChangeNotifierProvider(create: (_) => LikeNotifier()),
//         ChangeNotifierProvider(create: (_) => MyProfileLikeNotifier()),
//         ChangeNotifierProvider(create: (_) => PostProvider()),
//         ChangeNotifierProvider(create: (_) => ThemeProvider()),
//       ],
//       child: MyApp(pinSet: savedPin != null),
//     ),
//   );
// }

// class MyApp extends StatelessWidget {
//   final bool pinSet;
//   const MyApp({super.key, required this.pinSet});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'LocalBuzz',
//       debugShowCheckedModeBanner: false,
//       themeMode: ThemeMode.system,

//       // ✅ Your light theme
//       theme: ThemeData(
//         brightness: Brightness.light,
//         scaffoldBackgroundColor: Colors.white,
//         appBarTheme: const AppBarTheme(
//           backgroundColor: Colors.white,
//           foregroundColor: Colors.black,
//           elevation: 1,
//         ),
//         iconTheme: const IconThemeData(color: Colors.black),
//         textTheme: const TextTheme(
//           bodyMedium: TextStyle(color: Colors.black),
//         ),
//         useMaterial3: true,
//       ),

//       // ✅ Your dark theme
//       darkTheme: ThemeData(
//         brightness: Brightness.dark,
//         scaffoldBackgroundColor: Colors.black,
//         appBarTheme: const AppBarTheme(
//           backgroundColor: Colors.black,
//           foregroundColor: Colors.white,
//           elevation: 0,
//         ),
//         iconTheme: const IconThemeData(color: Colors.white),
//         textTheme: const TextTheme(
//           bodyMedium: TextStyle(color: Colors.white),
//         ),
//         useMaterial3: true,
//       ),

//       // ✅ Dynamic home logic
//       home: StreamBuilder<User?>(
//         stream: FirebaseAuth.instance.authStateChanges(),
//         builder: (context, snapshot) {
//           if (snapshot.connectionState == ConnectionState.waiting) {
//             return const Scaffold(
//               body: Center(child: CircularProgressIndicator()),
//             );
//           } else if (snapshot.hasData) {
//             return pinSet ? const EnterPinScreen() : const BottomNavScreen();
//           } else {
//             return const LoginScreen();
//           }
//         },
//       ),
//     );
//   }
// }



// import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'package:firebase_auth/firebase_auth.dart';
// import 'package:local_buzz_app/screens/home_feed_screen.dart';
// import 'package:local_buzz_app/screens/my_profile_screen.dart';
// import 'package:local_buzz_app/screens/otherscreens/fontsize_provider.dart';
// import 'package:local_buzz_app/screens/public_user_pofile.dart';
// import 'package:provider/provider.dart';
// import 'package:shared_preferences/shared_preferences.dart';

// import 'package:local_buzz_app/allSettings/enter_pin_screen.dart';
// import 'package:local_buzz_app/bottomnav.dart';
// import 'package:local_buzz_app/screens/login_screen.dart';
// import 'package:local_buzz_app/screens/otherscreens/bookmarks_provider.dart';
// import 'package:local_buzz_app/screens/otherscreens/likes_provider.dart';
// import 'package:local_buzz_app/screens/otherscreens/notification_seen_provider.dart';
// import 'package:local_buzz_app/screens/otherscreens/post_provider.dart';
// import 'package:local_buzz_app/screens/otherscreens/theme_provider.dart';

// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   await Firebase.initializeApp();

//   final prefs = await SharedPreferences.getInstance();
//   final savedPin = prefs.getString('app_pin');

//   runApp(
//     MultiProvider(
//       providers: [
//         ChangeNotifierProvider(create: (_) => NotificationSeenProvider()),
//         ChangeNotifierProvider(create: (_) => LocationProvider()),
//         ChangeNotifierProvider(create: (_) => BookmarksProvider()),
//         ChangeNotifierProvider(create: (_) => LikesProvider()),
//         ChangeNotifierProvider(create: (_) => LikeNotifier()),
//         ChangeNotifierProvider(create: (_) => MyProfileLikeNotifier()),
//         ChangeNotifierProvider(create: (_) => PostProvider()),
//         ChangeNotifierProvider(create: (_) => ThemeProvider()),
//         ChangeNotifierProvider(create: (_) => FontSizeProvider()),  
//       ],
//       child: MyApp(pinSet: savedPin != null),
//     ),
//   );
// }

// class MyApp extends StatelessWidget {
//   final bool pinSet;
//   const MyApp({super.key, required this.pinSet});

//   @override
//   Widget build(BuildContext context) {
//     return Consumer<ThemeProvider>(
//       builder: (context, themeProvider, _) {
//         return MaterialApp(
//           title: 'LocalBuzz',
//           debugShowCheckedModeBanner: false,
//           themeMode: themeProvider.themeMode, // 🔄 Dynamic theme
//           theme: ThemeData(
//             brightness: Brightness.light,
//             scaffoldBackgroundColor: Colors.white,
//             appBarTheme: const AppBarTheme(
//               backgroundColor: Colors.white,
//               foregroundColor: Colors.black,
//               elevation: 1,
//             ),
//             iconTheme: const IconThemeData(color: Colors.black),
//             textTheme: const TextTheme(
//               bodyMedium: TextStyle(color: Colors.black),
//             ),
//             useMaterial3: true,
//           ),
//           darkTheme: ThemeData(
//             brightness: Brightness.dark,
//             scaffoldBackgroundColor: Colors.black,
//             appBarTheme: const AppBarTheme(
//               backgroundColor: Colors.black,
//               foregroundColor: Colors.white,
//               elevation: 0,
//             ),
//             iconTheme: const IconThemeData(color: Colors.white),
//             textTheme: const TextTheme(
//               bodyMedium: TextStyle(color: Colors.white),
//             ),
//             useMaterial3: true,
//           ),
//           home: StreamBuilder<User?>(
//             stream: FirebaseAuth.instance.authStateChanges(),
//             builder: (context, snapshot) {
//               if (snapshot.connectionState == ConnectionState.waiting) {
//                 return const Scaffold(
//                   body: Center(child: CircularProgressIndicator()),
//                 );
//               } else if (snapshot.hasData) {
//                 return pinSet ? const EnterPinScreen() : const BottomNavScreen();
//               } else {
//                 return const LoginScreen();
//               }
//             },
//           ),
//         );
//       },
//     );
//   }
// } 



import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:local_buzz_app/firebase_options.dart';
import 'package:local_buzz_app/screens/home_feed_screen.dart';
import 'package:local_buzz_app/screens/my_profile_screen.dart';
import 'package:local_buzz_app/screens/otherscreens/fontsize_provider.dart';
import 'package:local_buzz_app/screens/otherscreens/username_prompt_screen.dart';
import 'package:local_buzz_app/screens/public_user_pofile.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'package:local_buzz_app/allSettings/enter_pin_screen.dart';
import 'package:local_buzz_app/bottomnav.dart';
import 'package:local_buzz_app/screens/login_screen.dart';
import 'package:local_buzz_app/screens/otherscreens/bookmarks_provider.dart';
import 'package:local_buzz_app/screens/otherscreens/likes_provider.dart';
import 'package:local_buzz_app/screens/otherscreens/notification_seen_provider.dart';
import 'package:local_buzz_app/screens/otherscreens/post_provider.dart';
import 'package:local_buzz_app/screens/otherscreens/theme_provider.dart';


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  final prefs = await SharedPreferences.getInstance();
  final savedPin = prefs.getString('app_pin');

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => NotificationSeenProvider()),
        ChangeNotifierProvider(create: (_) => LocationProvider()),
        ChangeNotifierProvider(create: (_) => BookmarksProvider()),
        ChangeNotifierProvider(create: (_) => LikesProvider()),
        ChangeNotifierProvider(create: (_) => LikeNotifier()),
        ChangeNotifierProvider(create: (_) => MyProfileLikeNotifier()),
        ChangeNotifierProvider(create: (_) => PostProvider()),
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
        ChangeNotifierProvider(create: (_) => FontSizeProvider()),
      ],
      child: MyApp(pinSet: savedPin != null),
    ),
  );
}

class MyApp extends StatelessWidget {
  final bool pinSet;
  const MyApp({super.key, required this.pinSet});

  @override
  Widget build(BuildContext context) {
    return Consumer<ThemeProvider>(
      builder: (context, themeProvider, _) {
        return MaterialApp(
          title: 'LocalBuzz',
          debugShowCheckedModeBanner: false,
          themeMode: themeProvider.themeMode,
          theme: ThemeData(
            brightness: Brightness.light,
            scaffoldBackgroundColor: Colors.white,
            appBarTheme: const AppBarTheme(
              backgroundColor: Colors.white,
              foregroundColor: Colors.black,
              elevation: 1,
            ),
            iconTheme: const IconThemeData(color: Colors.black),
            textTheme: const TextTheme(
              bodyMedium: TextStyle(color: Colors.black),
            ),
            useMaterial3: true,
          ),
          darkTheme: ThemeData(
            brightness: Brightness.dark,
            scaffoldBackgroundColor: Colors.black,
            appBarTheme: const AppBarTheme(
              backgroundColor: Colors.black,
              foregroundColor: Colors.white,
              elevation: 0,
            ),
            iconTheme: const IconThemeData(color: Colors.white),
            textTheme: const TextTheme(
              bodyMedium: TextStyle(color: Colors.white),
            ),
            useMaterial3: true,
          ),
          home: SplashCheck(pinSet: pinSet),
        );
      },
    );
  }
}

class SplashCheck extends StatelessWidget {
  final bool pinSet;
  const SplashCheck({super.key, required this.pinSet});

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<User?>(
      future: FirebaseAuth.instance.authStateChanges().first,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(body: Center(child: CircularProgressIndicator()));
        }

        final user = snapshot.data;
        if (user == null) return const LoginScreen();

        return FutureBuilder<DocumentSnapshot>(
          future: FirebaseFirestore.instance.collection('users').doc(user.uid).get(),
          builder: (context, profileSnap) {
            if (!profileSnap.hasData) {
              return const Scaffold(body: Center(child: CircularProgressIndicator()));
            }

            final data = profileSnap.data?.data() as Map<String, dynamic>?;

            if (data == null || !data.containsKey('username')) {
              return const UsernamePromptScreen();
            }

            return pinSet ? const EnterPinScreen() : const BottomNavScreen();
          },
        );
      },
    );
  }
}